# Generated by Django 6.0.3 on 2026-03-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_type', models.CharField(choices=[('practice', 'Practice'), ('tournament', 'Tournament')], max_length=20)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(choices=[('setter', 'Setter'), ('libero', 'Libero'), ('middle_blocker', 'Middle Blocker'), ('outside_hitter', 'Outside Hitter'), ('opposite', 'Opposite')], max_length=20)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=100)),
                ('injury_date', models.DateField()),
                ('recovery_period', models.CharField(help_text='e.g. 2 weeks, 1 month', max_length=100)),
                ('current_status', models.CharField(choices=[('active', 'Active (Injured)'), ('recovering', 'Recovering'), ('cleared', 'Cleared to Play')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='core.player')),
            ],
            options={
                'ordering': ['-injury_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_attempts', models.PositiveIntegerField(default=0)),
                ('successful_attacks', models.PositiveIntegerField(default=0)),
                ('blocks_attempted', models.PositiveIntegerField(default=0)),
                ('successful_blocks', models.PositiveIntegerField(default=0)),
                ('total_serves', models.PositiveIntegerField(default=0)),
                ('successful_serves', models.PositiveIntegerField(default=0)),
                ('service_errors', models.PositiveIntegerField(default=0)),
                ('reception_success', models.PositiveIntegerField(default=0)),
                ('digs', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('points_scored', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.player')),
            ],
            options={
                'ordering': ['-match__match_date'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
