# Generated by Django 6.0.3 on 2026-03-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='attack_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='reception_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('jump_training', 'Jump Training'), ('spike_training', 'Spike / Attack Training'), ('serve_training', 'Serve Training'), ('block_training', 'Block Training'), ('defense_drills', 'Defense & Reception Drills'), ('fitness', 'Fitness & Conditioning'), ('team_tactics', 'Team Tactics & Strategy'), ('scrimmage', 'Scrimmage / Practice Match'), ('other', 'Other')], max_length=30)),
                ('training_date', models.DateField()),
                ('duration', models.CharField(help_text='e.g. 1 hour, 45 minutes', max_length=60)),
                ('performance_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='core.player')),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
    ]
