# Generated by Django 6.0.3 on 2026-03-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerperformance_attack_errors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matches_played',
        ),
    ]
